name: geniego
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.20.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  connectivity_plus: ^6.0.3
  intl_phone_number_input: ^0.7.4
  dart_ipify: ^1.1.1
  flutter_dotenv: ^5.0.2

  # Images
  lottie: ^3.1.3
  dotlottie_loader: ^0.0.4
  flutter_svg: ^2.0.16
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  country_flags: ^3.0.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  shimmer: ^3.0.0
  custom_refresh_indicator: ^4.0.1
  image_picker: ^1.1.2
  path: ^1.9.0
  universal_html: ^2.2.4
  flutter_background_service: ^5.1.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  cached_network_image: ^3.4.1


  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animated/
    - assets/icons/payment_methods/
    - assets/images/static/
    - .env

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800